abs_pattern: .na.character
abs_skip: "\\w*(SEM|BEM).dat$|^.*Waterfall( ?)Plot( ?)(Blank|Sample).dat$"
abs_file_ext: "dat"
abs_recurse_read: FALSE
eem_pattern: .na.character
eem_skip: "\\w*ABS.dat$|.*Abs( ?)Spectra( ?)Graphs.dat$"
eem_file_ext: "dat"
eem_recurse_read: FALSE
eem_import_func: "aqualog"
meta_file:  .na.character
meta_sheet: .na.character
meta_validate: TRUE
iblank_pattern: "BEM$|Waterfall ?Plot ?Blank"
sblank_pattern: "Blank|blank|BLK"
check_pattern: "Tea|tea"
blank_validate: TRUE
ex_clip:
  - 247
  - 450
em_clip:
  - 247
  - 600
type:
  - TRUE
  - TRUE
  - TRUE
  - TRUE
width:
  - 16
  - 3
  - 30
  - 10
interpolate:
  - TRUE
  - TRUE
  - FALSE
  - FALSE
method: 1
cores: 1
cuvle: 1
index_method: "eemanalyzeR"
tolerance: 0.2
return: "wide"
qaqc_dir: .na.character
qaqc_method: .na.character
filename: "eemanalyzeR-output"
output_dir: .na.character
spectra_to_csv: FALSE
sum_plot: TRUE
package_version: .na.character
