#' @keywords internal
"_PACKAGE"

utils::globalVariables(c(".pkgenv", "value"))

## usethis namespace: start

#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr group_by
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom eemR eem_biological_index
#' @importFrom eemR eem_coble_peaks
#' @importFrom eemR eem_cut
#' @importFrom eemR eem_fluorescence_index
#' @importFrom eemR eem_humification_index
#' @importFrom eemR eem_inner_filter_effect
#' @importFrom eemR eem_read
#' @importFrom fs dir_tree
#' @importFrom fs path_norm
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_contour
#' @importFrom ggplot2 geom_contour_filled
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_ribbon
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 theme
#' @importFrom ggpubr ggarrange
#' @importFrom ggrepel geom_text_repel
#' @importFrom grDevices colorRampPalette
#' @importFrom lubridate parse_date_time
#' @importFrom magrittr %>%
#' @importFrom pals parula
#' @importFrom parallel detectCores
#' @importFrom pbapply pblapply
#' @importFrom plyr join
#' @importFrom plyr round_any
#' @importFrom pracma interp2
#' @importFrom purrr discard
#' @importFrom purrr list_transpose
#' @importFrom purrr quietly
#' @importFrom purrr reduce
#' @importFrom rappdirs user_data_dir
#' @importFrom rlang .data
#' @importFrom rlang as_string
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang is_interactive
#' @importFrom rlang local_interactive
#' @importFrom staRdom abs_fit_slope
#' @importFrom staRdom abs_parms
#' @importFrom staRdom eem_exclude
#' @importFrom staRdom eem_extend2largest
#' @importFrom staRdom eem_interp
#' @importFrom staRdom eem_matmult
#' @importFrom staRdom eem_red2smallest
#' @importFrom staRdom eem_rem_scat
#' @importFrom staRdom ggeem
#' @importFrom stats na.omit
#' @importFrom stats sd
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_split_i
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tools file_ext
#' @importFrom utils capture.output
#' @importFrom utils file.edit
#' @importFrom utils file_test
#' @importFrom utils read.csv
#' @importFrom utils write.csv
#' @importFrom utils write.table
#' @importFrom yaml read_yaml
#' @importFrom zoo na.approx
#' @importFrom zoo na.spline
## usethis namespace: end
NULL
