#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cowplot plot_grid
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr group_by
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom eemR eem_biological_index
#' @importFrom eemR eem_coble_peaks
#' @importFrom eemR eem_cut
#' @importFrom eemR eem_fluorescence_index
#' @importFrom eemR eem_humification_index
#' @importFrom eemR eem_inner_filter_effect
#' @importFrom eemR eem_read
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme
#' @importFrom ggpubr ggarrange
#' @importFrom grDevices colorRampPalette
#' @importFrom lubridate parse_date_time
#' @importFrom magrittr %>%
#' @importFrom pals parula
#' @importFrom parallel detectCores
#' @importFrom pbapply pblapply
#' @importFrom plyr join
#' @importFrom plyr round_any
#' @importFrom pracma interp2
#' @importFrom purrr discard
#' @importFrom purrr list_transpose
#' @importFrom rappdirs user_data_dir
#' @importFrom readxl read_excel
#' @importFrom rlang .data
#' @importFrom rlang as_string
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang is_interactive
#' @importFrom rlang local_interactive
#' @importFrom staRdom abs_fit_slope
#' @importFrom staRdom abs_parms
#' @importFrom staRdom eem_exclude
#' @importFrom staRdom eem_extend2largest
#' @importFrom staRdom eem_interp
#' @importFrom staRdom eem_matmult
#' @importFrom staRdom eem_red2smallest
#' @importFrom staRdom eem_rem_scat
#' @importFrom staRdom ggeem
#' @importFrom stats na.omit
#' @importFrom stats sd
#' @importFrom stringr str_extract_all
#' @importFrom tidyr pivot_longer
#' @importFrom tidyselect matches
#' @importFrom tools file_ext
#' @importFrom usethis use_data
#' @importFrom utils file_test
#' @importFrom tidyr pivot_wider
#' @importFrom utils capture.output
#' @importFrom utils read.csv
#' @importFrom utils write.csv
#' @importFrom utils write.table
#' @importFrom zoo na.spline
## usethis namespace: end
NULL
